// SPDX-License-Identifier: CC-BY-SA-4.0
= Code of Conduct
:toc:

== Our Pledge

We pledge to make participation in this project a harassment-free
experience for everyone, regardless of age, body size, disability,
ethnicity, gender identity and expression, level of experience,
nationality, personal appearance, race, religion, or sexual identity and
orientation.

== Our Standards

Examples of behaviour that creates a positive environment:

* Being respectful of differing viewpoints and experiences
* Giving and accepting constructive feedback
* Focusing on what is best for the community
* Showing empathy towards other community members

Examples of unacceptable behaviour:

* Harassment, trolling, or insulting comments
* Publishing others' private information without permission
*Other conduct which could reasonably be considered inappropriate

== Enforcement

Report violations to **@@CONDUCT_CONTACT@@**. All complaints will be
reviewed and investigated promptly and fairly. Maintainers are obligated to
respect the privacy and security of the reporter.

== Attribution

Adapted from the Contributor Covenant, version 2.1.
